'use client'

import type { Metadata } from "next";
import { Card, Flex, Text, Authenticator } from "@aws-amplify/ui-react";
import { AuthSession, fetchAuthSession, signOut } from "aws-amplify/auth";

// https://mui.com/toolpad/core/react-dashboard-layout/
import { NextAppProvider } from '@toolpad/core/nextjs';
import { Session, type Navigation } from '@toolpad/core/AppProvider';
import { createTheme } from '@mui/material/styles';
import DashboardIcon from '@mui/icons-material/Dashboard';
import { DashboardLayout } from '@toolpad/core/DashboardLayout';
import TimelineIcon from '@mui/icons-material/Timeline';
import { Inter } from "next/font/google";
import theme from "./theme/theme";
import "./app.css";
import { useEffect, useState } from "react";
import { AuthEventType } from "@aws-sdk/client-cognito-identity-provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type ISignOut = (data?: AuthEventType) => void

const NAVIGATION: Navigation = [
  {
    kind: 'header',
    title: 'Main items',
  },
  {
    segment: 'admin',
    title: 'Admin',
    icon: <DashboardIcon />,
  },
  {
    segment: 'users',
    title: 'Users',
    icon: <TimelineIcon />,
  },
];


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [group, setGroup] = useState<string[]>([''])
  
  async function fetchSession() {
    const authSession: AuthSession = await fetchAuthSession()
    const groups = authSession?.tokens?.accessToken?.payload["cognito:groups"];
    console.log('GROUPS---->', groups, authSession)
    setGroup(groups as string[])
  }
  
  async function signOutOfApp() {
    await signOut()
  }

  useEffect(() => {
    fetchSession();
  }, []);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authenticator loginMechanisms={['email']}>
          {({ signOut: ISignOut, user }) => {
            console.log(user)

            const session: Session = {
                  // TODO: fetch profile information from a db
                  user: {
                    name: 'Matt Olsen',
                    email: user?.signInDetails?.loginId as string,
                    image: 'https://avatars.githubusercontent.com/u/89269242?v=4',
                  },
            }
            
            return (
              <NextAppProvider
                navigation={NAVIGATION}
                theme={theme}
                authentication={{ signOut: async () => {await signOut()}, signIn: async () => {console.log('sign in')}}}
                session={session}
              >
                <DashboardLayout>
                  {children}

                </DashboardLayout>
              </NextAppProvider>
            )
          }}
        </Authenticator>
      </body>
    </html>
  );
}
