import type { Metadata } from "next";
import { NextAppProvider } from '@toolpad/core/nextjs';
import { type Navigation } from '@toolpad/core/AppProvider';
import { createTheme } from '@mui/material/styles';
import DashboardIcon from '@mui/icons-material/Dashboard';
import { DashboardLayout } from '@toolpad/core/DashboardLayout';
import TimelineIcon from '@mui/icons-material/Timeline';
import { Inter } from "next/font/google";
import theme from "./theme/theme";
import "./app.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAVIGATION: Navigation = [
  {
    kind: 'header',
    title: 'Main items',
  },
  {
    segment: 'admin',
    title: 'Admin',
    icon: <DashboardIcon />,
  },
  {
    segment: 'users',
    title: 'Users',
    icon: <TimelineIcon />,
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAppProvider
          navigation={NAVIGATION}
          theme={theme}
        >
          <DashboardLayout>
            {children}
          </DashboardLayout>
        </NextAppProvider>
      </body>
    </html>
  );
}
