'use client'

import type { Metadata } from "next";
import { Card, Flex, Text, Authenticator } from "@aws-amplify/ui-react";
import { AuthSession, fetchAuthSession, signOut } from "aws-amplify/auth";

// https://mui.com/toolpad/core/react-dashboard-layout/
import { NextAppProvider } from '@toolpad/core/nextjs';
import { Session, type Navigation } from '@toolpad/core/AppProvider';
// import { createTheme } from '@mui/material/styles';
import DashboardIcon from '@mui/icons-material/Dashboard';
import { DashboardLayout } from '@toolpad/core/DashboardLayout';
import TimelineIcon from '@mui/icons-material/Timeline';
import { Inter } from "next/font/google";
import theme from "./theme/theme";
import "./app.css";
import "@aws-amplify/ui-react/styles.css";  // need this to style the auth componentss

import { useEffect, useState } from "react";
import { AuthEventType } from "@aws-sdk/client-cognito-identity-provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {  //TODO: Move this to the intro page
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type ISignOut = (data?: AuthEventType) => void

const NAVIGATION: Record<string, Navigation> = {
  settings: [{
    kind: 'header',
    title: 'Settings',
  },
  {
    segment: 'settings',
    title: 'Users & Permissions',
    icon: <DashboardIcon />,
  }
  ],
  users: [{
    segment: 'programs',
    title: 'Programming',
    icon: <TimelineIcon />,
  }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [authGroups, setAuthGroups] = useState<string[]>([])
  const [navigation, setNavigation] = useState<Navigation>([])
  const [user, setUser] = useState<any>(null)
  
  async function fetchSession() {
    const authSession: AuthSession = await fetchAuthSession()
    const groups = authSession?.tokens?.accessToken?.payload["cognito:groups"];
    setAuthGroups(groups as string[])

    console.log('AUTH GROUPS', groups)

    if (!groups) {
      setNavigation([
        NAVIGATION.header[0],
      ])
      return
    }

    setNavigation([
      ...((groups as string[]).includes('EVERYONE') ? NAVIGATION.users : []),
      ...((groups as string[]).includes('ADMIN') ? NAVIGATION.settings: []),
    ])
  }
  
  async function signOutOfApp() {
    await signOut()
  }

  useEffect(() => {
    fetchSession();
  }, [user]);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authenticator loginMechanisms={['email']}>
          {({ signOut: ISignOut, user }) => {
            console.log(user)
            setUser(user)

            const session: Session = {
                  // TODO: fetch profile information from a db
                  user: {
                    name: 'Matt Olsen',
                    email: user?.signInDetails?.loginId as string,
                    image: 'https://avatars.githubusercontent.com/u/89269242?v=4',
                  },
            }
            
            return (
              <NextAppProvider
                key={JSON.stringify(navigation)}
                navigation={navigation}
                theme={theme}
                authentication={{ signOut: async () => {await signOut()}, signIn: async () => {console.log('sign in')}}}
                session={session}
              >
                <DashboardLayout>
                  {children}

                </DashboardLayout>
              </NextAppProvider>
            )
          }}
        </Authenticator>
      </body>
    </html>
  );
}
